// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/personal-secretary/BriefRailSecretaryMobile.tsx": () => import("../components/mockups/personal-secretary/BriefRailSecretaryMobile.tsx"),
  "./components/mockups/personal-secretary/ChatFirstSecretary.tsx": () => import("../components/mockups/personal-secretary/ChatFirstSecretary.tsx"),
  "./components/mockups/personal-secretary/ChatFirstSecretaryMobile.tsx": () => import("../components/mockups/personal-secretary/ChatFirstSecretaryMobile.tsx"),
  "./components/mockups/personal-secretary/DragSheetSecretaryMobile.tsx": () => import("../components/mockups/personal-secretary/DragSheetSecretaryMobile.tsx"),
  "./components/mockups/personal-secretary/InboxSecretaryCalmPriority.tsx": () => import("../components/mockups/personal-secretary/InboxSecretaryCalmPriority.tsx"),
  "./components/mockups/personal-secretary/InboxSecretaryMobile.tsx": () => import("../components/mockups/personal-secretary/InboxSecretaryMobile.tsx"),
  "./components/mockups/personal-secretary/OpalescentPearlSecretaryMobile.tsx": () => import("../components/mockups/personal-secretary/OpalescentPearlSecretaryMobile.tsx"),
  "./components/mockups/personal-secretary/SecretaryCommandCenter.tsx": () => import("../components/mockups/personal-secretary/SecretaryCommandCenter.tsx"),
  "./components/mockups/personal-secretary/SecretaryDaybookMobile.tsx": () => import("../components/mockups/personal-secretary/SecretaryDaybookMobile.tsx"),
  "./components/mockups/personal-secretary/SecretaryPulseBoard.tsx": () => import("../components/mockups/personal-secretary/SecretaryPulseBoard.tsx"),
  "./components/mockups/personal-secretary/SecretaryTriageTimelineMobile.tsx": () => import("../components/mockups/personal-secretary/SecretaryTriageTimelineMobile.tsx"),
  "./components/mockups/personal-secretary/SoftGlassDragSheetSecretaryMobile.tsx": () => import("../components/mockups/personal-secretary/SoftGlassDragSheetSecretaryMobile.tsx")
};
